PSTodos.Mvc/ViewModels/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PSTodos.Mvc.ViewModels
{
    public class UsuarioViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(20, ErrorMessage = "O campo {0} deve conter no máximo {1} caracteres.")]
        public string Login { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(250, ErrorMessage = "O campo {0} deve conter no máximo {1} caracteres.")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(150, ErrorMessage = "O campo {0} deve conter no máximo {1} caracteres.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [MaxLength(50, ErrorMessage = "O campo {0} deve conter no máximo {1} caracteres.")]
        public string Senha { get; set; }

        public bool Ativo { get; set; }

        public DateTime DtInclusao { get; set; }
        
        public IEnumerable<PerfilViewModel> Perfis { get; set; }
    }
}

PSTodos.Mvc/Controllers/PerfisController.cs
using PSTodos.Mvc.Notifications;
using PSTodos.RESTServices;
using PSTodos.RESTServices.ViewModels;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace PSTodos.Mvc.Controllers
{
    public class PerfisController : Controller
    {
        private readonly IPerfilRESTService _service;

        public PerfisController(IPerfilRESTService service)
        {
            _service = service;
        }
        // GET: Perfis
        public ActionResult Index()
        {
            var vm = _service.Listar();
            return View(vm.Result);
        }

        public ActionResult Create()
        {
            var vm = new PerfilViewModel();

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(PerfilViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                this.AddToastMessage("", "Falha ao cadastrar Perfil.", ToastType.Error);
                return View("Create", vm);
            }

            var result = _service.Cadastrar(vm);

            if (result.Success)
            {
                this.AddToastMessage("", "Perfil cadastrado com sucesso.", ToastType.Success);
                return RedirectToAction("Index");
            }
            else
            {
                this.AddToastMessage("", "Falha ao cadastrar Perfil.", ToastType.Error);
                return View("Create", vm);
            }
        }

        public ActionResult Edit(int id)
        {
            var vm = _service.Obter(id);

            return View("Edit", vm.Result);
        }

        [HttpPut]
        public ActionResult Edit(int id, PerfilViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                this.AddToastMessage("", "Falha ao alterar Perfil.", ToastType.Error);
                return View("Edit", vm);
            }

            var result = _service.Editar(id, vm);

            if (result.Success)
            {
                this.AddToastMessage("", "Perfil alterado com sucesso.", ToastType.Success);
                return RedirectToAction("Index");
            }
            else
            {
                this.AddToastMessage("", "Falha ao Alterar Perfil.", ToastType.Error);
                return View("Edit", vm);
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var result = _service.Remover(id);

            if(result.Success)
                this.AddToastMessage("", "Perfil removido com sucesso.", ToastType.Success);
            else
                this.AddToastMessage("", "Falha ao remover perfil.", ToastType.Error);
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult ListarPerfis()
        {
            var vm = _service.Listar();
            
            return PartialView("_ListarPerfisPartial", vm.Result);
        }
    }
}

PSTodos.Mvc/Controllers/UsuariosController.cs
using PSTodos.Mvc.Notifications;
using PSTodos.RESTServices;
using PSTodos.RESTServices.ViewModels;
using System;
using System.Web.Mvc;

namespace PSTodos.Mvc.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRESTService _service;

        public UsuariosController(IUsuarioRESTService service)
        {
            _service = service;
        }

        public ActionResult Index()
        {
            var vm = _service.Listar();

            return View(vm.Result);
        }

        public ActionResult Create()
        {
            var vm = new UsuarioViewModel();
            vm.DtInclusao = DateTime.Now;

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(UsuarioViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                this.AddToastMessage("", "Falha ao cadastrar Usuário.", ToastType.Error);
                return View("Create", vm);
            }

            var result = _service.Cadastrar(vm);

            if(result.Success)
            {
                this.AddToastMessage("", "Usuário cadastrado com sucesso.", ToastType.Success);
                return RedirectToAction("Edit", new { id = result.Result.Id });
            }
            else
            {
                this.AddToastMessage("", "Falha ao cadastrar Usuário.", ToastType.Error);
                return View("Create", vm);
            }
        } 

        public ActionResult Edit(int id)
        {
            var vm = _service.Obter(id);

            return View("Edit", vm.Result);
        }

        [HttpPut]
        public ActionResult Edit(int id, UsuarioViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                this.AddToastMessage("", "Falha ao alterar Usuário.", ToastType.Error);
                return View("Edit", vm);
            }

            var result = _service.Editar(id, vm);

            if(result.Success)
            {
                this.AddToastMessage("", "Usuário alterado com sucesso.", ToastType.Success);
                return RedirectToAction("Index");
            }
            else
            {
                this.AddToastMessage("Erro", "Falha ao alterar Usuário.", ToastType.Error);
                return View("Edit", vm);
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var result = _service.Remover(id);

            if(result.Success)
                this.AddToastMessage("", "Usuário removido com sucesso.", ToastType.Success);
            else
                this.AddToastMessage("", "Falha ao remover Usuário.", ToastType.Success);
            return RedirectToAction("Index");
        }
    }

}

PSTodos.Mvc/Controllers/UsuariosPerfisController.cs
using PSTodos.Mvc.Notifications;
using PSTodos.RESTServices;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PSTodos.Mvc.Controllers
{
    public class UsuariosPerfisController : Controller
    {
        private readonly IUsuarioPerfilRESTService _service;

        public UsuariosPerfisController(IUsuarioPerfilRESTService service)
        {
            _service = service;
        }

        [HttpPost]
        public ActionResult AdicionarUsuarioPerfil(int usuarioId, int perfilId)
        {
            var vm = _service.AdicionarPerfil(usuarioId, perfilId);

            if (vm.Success)
            {
                this.AddToastMessage("", "Perfil atribuído ao Usuário", ToastType.Success);
            }
            else
            {
                this.AddToastMessage("", "Falha ao atribuir Perfil ao Usuário", ToastType.Error);
            }
            return RedirectToAction("Edit", "Usuarios", new { Id = usuarioId });
        }


        [HttpPost]
        public ActionResult RemoverUsuarioPerfil(int usuarioId, int perfilId)
        {
            var vm = _service.RemoverPerfil(usuarioId, perfilId);

            if (vm.Success)
            {
                this.AddToastMessage("", "Perfil removido do Usuário", ToastType.Success);
            }
            else
            {
                this.AddToastMessage("", "Falha ao remover Perfil do Usuário", ToastType.Error);
            }

            return RedirectToAction("Edit", "Usuarios", new { Id = usuarioId });
        }

    }
}

PSTodos.Mvc/Views/Usuarios/Create.cshtml
@model PSTodos.RESTServices.ViewModels.UsuarioViewModel
@{
    ViewBag.Title = "Cadastro";
}

<div class="section">
    <div class="container">
        <h4 style="float: left">Cadastro de Usuário</h4>
        <div class="row">
            @using (Html.BeginForm("Create", "Usuarios", FormMethod.Post, new { @class = "col s12", @role="form" }))
            {        
                <div class="row">
                    <div class="input-field col s6">                       
                        @Html.EditorFor(m => m.Login, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Login)
                        @Html.ValidationMessageFor(m => m.Login)
                    </div>
                    <div class="input-field col s6">
                        @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Nome)
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">                     
                        @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Email, new { @data_error = "Email inválido." })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                    <div class="input-field col s6">           
                        @Html.EditorFor(m => m.Senha, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Senha)
                        @Html.ValidationMessageFor(m => m.Senha)
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        @Html.CheckBoxFor(m => m.Ativo, new { @type = "checkbox" })

                        @Html.LabelFor(m => m.Ativo)
                    </div>
                    <div class="input-field col s6">
                        <input disabled value="@Model.DtInclusao.ToString("dd/MM/yyyy")" id="dt_inclusao" type="text" class="validate">
                        <label for="dt_inclusao">Data de Inclusão</label>
                    </div>
                </div>
                <button class="waves-effect waves-light btn"><i class="material-icons left">save</i>salvar</button>
            }
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $('input:hidden').each(function (index, element) {
            $(element).appendTo($(element).parent());
        });
    </script>
}

PSTodos.Mvc/Views/Usuarios/Edit.cshtml
@model PSTodos.RESTServices.ViewModels.UsuarioViewModel
@{
    ViewBag.Title = "Alteração";
}

<div class="section">
    <div class="container">
        <h4 style="float: left">Cadastro de Usuário</h4>
        <div class="row">
            @using (Html.BeginForm("Edit", "Usuarios", FormMethod.Post, new { @class = "col s12", @role = "form" }))
            {
                @Html.HttpMethodOverride(HttpVerbs.Put)
                <div class="row">
                    <div class="input-field col s6">
                        @Html.EditorFor(m => m.Login, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Login)
                        @Html.ValidationMessageFor(m => m.Login)
                    </div>
                    <div class="input-field col s6">
                        @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Nome)
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Email, new { @data_error = "Email inválido." })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                    <div class="input-field col s6">
                        @Html.EditorFor(m => m.Senha, new { htmlAttributes = new { @class = "validate" } })
                        @Html.LabelFor(m => m.Senha)
                        @Html.ValidationMessageFor(m => m.Senha)
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        @Html.CheckBoxFor(m => m.Ativo, new { @type = "checkbox" })
                        @Html.LabelFor(m => m.Ativo)
                    </div>
                    <div class="input-field col s6">
                        <input disabled value="@Model.DtInclusao.ToString("dd/MM/yyyy")" id="dt_inclusao" type="text" class="validate">
                        <label for="dt_inclusao">Data de Inclusão</label>
                    </div>
                </div>
                <button class="waves-effect waves-light btn"><i class="material-icons left">save</i>salvar</button>
            }
        </div>

        <div class="row">
            <br><br>
            <h5>Perfis do Usuário</h5>
            <div class="row">
                <div class="input-field col s10">
                    @{ Html.RenderAction("ListarPerfis", "Perfis"); }
                </div>
                <div class="input-field col s2">
                    @using (Html.BeginForm("AdicionarUsuarioPerfil", "UsuariosPerfis", FormMethod.Post))
                    {
                        @Html.Hidden("usuarioId", Model.Id)
                        <input type="hidden" name="perfilId" id="perfilId" />
                        <button class="waves-effect waves-light btn" id="adicionar_perfil"><i class="material-icons">add</i></button>
                    }
                    
                </div>
            </div>
            <div class="row">
                @if (Model.Perfis.Any())
                {
                    <table class="highlight bordered">
                        <thead>
                            <tr>
                                <th data-field="perfil">Perfil</th>
                                <th data-field="excluir">Remover</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Perfis)
                            {
                                <tr>
                                    <td>@item.Nome</td>
                                    <td>
                                        @using (Html.BeginForm("RemoverUsuarioPerfil", "UsuariosPerfis", FormMethod.Post))
                                        {
                                            @Html.Hidden("usuarioId", Model.Id)
                                            @Html.Hidden("perfilId", item.Id)
                                            <button class="waves-effect waves-light btn red" style="padding: 0 1rem"><i class="material-icons">delete</i></button>
                                        }                                      
                                    </td>
                                </tr>
                            }                       
                        </tbody>
                    </table>
                }
                else
                {
                    <h5>Nenhum Perfil cadastrado.</h5>
                    }
                
            </div>
        </div>  

    </div>
</div>

@section Scripts
{
    <script>
        $('input:hidden').each(function (index, element) {
            $(element).appendTo($(element).parent());
        });

        $('#perfis').change(function () {
            $('#perfilId').val($(this).val());
        })
    </script>
}

PSTodos.Mvc/Views/Usuarios/Index.cshtml
@model List<PSTodos.RESTServices.ViewModels.UsuarioViewModel>

@{
    ViewBag.Title = "Index";
}

<div class="section">
    <div class="container">
        <h4 style="float: left">Listagem de Usuários</h4>
        <div style="float: right; margin-top: 20px;">
            <a class="waves-effect waves-light btn teal" href="@Url.Action("Create", "Usuarios")"><i class="material-icons left">add</i>Novo Registro</a>
        </div>
        <br /><br />
        @if (Model.Any())
        {
            <table class="highlight bordered">
                <thead>
                    <tr>
                        <th data-field="id">Id</th>
                        <th data-field="login">Login</th>
                        <th data-field="nome">Nome</th>
                        <th data-field="email">Email</th>
                        <th data-field="senha">Senha</th>
                        <th data-field="ativo">Status</th>
                        <th data-field="acoes">Ações</th>
                    </tr>
                </thead>
                <tbody>
                
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Login</td>
                                <td>@item.Nome</td>
                                <td>@item.Email</td>
                                <td>@item.Senha</td>
                                @if (item.Ativo)
                                {
                                    <td class="center-align"><span class="new badge green" data-badge-caption="Ativo" style="float: left"></span></td>
                                }
                                else
                                {
                                    <td class="center-align"><span class="new badge red" data-badge-caption="Inativo" style="float: left"></span></td>
                                }
                                <td>                  

                                    @using (Html.BeginForm("Delete", "Usuarios", new { id = item.Id }))
                                    {
                                        @Html.HttpMethodOverride(HttpVerbs.Delete)
                                        <a class="waves-effect waves-light btn" style="padding: 0 1rem" href="@Url.Action("Edit", "Usuarios", new { id = item.Id })"><i class="material-icons">edit</i></a>
                                        <button class="waves-effect waves-light btn red" style="padding: 0 1rem" type="submit"><i class="material-icons">delete</i></button>
                                    }


                                </td>
                            </tr>
                        }
                </tbody>
            </table>
        }
        else
        {
            <h5>Nenhum resultado.</h5>
        }
    </div>
</div>